version: '3'
# Specifies the version of the Docker Compose file format being used.

services:
  app:
    # Defines a service named 'app' for the application container.
    image: suhaibtelfah/mavenproject:$IMAGE_TAG
    # Specifies the Docker image to be used for the 'app' service, with a tag determined by the $IMAGE_TAG environment variable.
    network_mode: "host"
    # Runs the 'app' container in the host network mode, sharing the host's networking stack.
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:assignment
      - JAVA_OPTS=-Xmx512m
      - IMAGE_TAG=${IMAGE_TAG}
      # Sets environment variables for the 'app' container, such as the active Spring profile, database connection URL, Java options, and the IMAGE_TAG value.
    depends_on:
      - db
      # Specifies that the 'app' service depends on the 'db' service, ensuring the database service is started before the application service.

  db:
    # Defines a service named 'db' for the database container.
    image: mysql:latest
    # Specifies the Docker image to be used for the 'db' service, using the latest version of the MySQL image.
    network_mode: "host"
    # Runs the 'db' container in the host network mode, sharing the host's networking stack.
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=assignment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@ssw0rd
      # Sets environment variables for the 'db' container, such as the root password, database name, user credentials, and password.
    volumes:
      - db-data:/var/lib/mysql
      # Mounts the 'db-data' volume to the '/var/lib/mysql' directory inside the 'db' container.

volumes:
  db-data:
  # Defines a named volume named 'db-data' used for persistent storage.
