version: '3'
services:
  app:
    image: suhaibtelfah/mavenproject:$IMAGE_TAG 
   
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:assignment
      - JAVA_OPTS=-Xmx512m
      - IMAGE_TAG=${IMAGE_TAG}
      
    depends_on:
      - db

  db:
    
    image: mysql:latest
   
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=assignment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=P@ssw0rd
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
