apiVersion: v1            # Defines the API version for the Kubernetes object
kind: Service             # Specifies the kind of Kubernetes object as a Service
metadata:
  name: assignment-service       # Specifies the name of the Service
spec:
  selector:
    app: assignment        # Selects the pods with labels matching 'app: assignment'
  ports:
  - protocol: TCP          # Sets the protocol for the port (TCP in this case)
    port: 90               # Sets the port number for the Service
    targetPort: 8090       # Sets the target port on the pods for the Service
