apiVersion: networking.k8s.io/v1     # Defines the API version for the Kubernetes object
kind: Ingress                        # Specifies the kind of Kubernetes object as an Ingress
metadata:
  name: assignment-ingress           # Specifies the name of the Ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"     # Specifies the Ingress class to be used as "nginx"
spec:
  tls:
  - hosts:
    - suhaibassignment.com                # Add your domain here for TLS configuration
    secretName: assignment-tls-secret     # Replace with the name of your Secret containing TLS certificates
  rules:
  - host: suhaibassignment.com            # Specifies the host/domain for the Ingress
    http:
      paths:
      - path: /                          # Specifies the path for the Ingress
        pathType: Exact                  # Specifies the type of the path as exact
        backend:
          service:
            name: assignment-service     # Specifies the name of the backend service
            port:
              number: 90                  # Specifies the port number of the backend service
