apiVersion: v1       # Defines the API version for the Kubernetes object
kind: Service        # Specifies the kind of Kubernetes object as a Service
metadata:
  name: mysql-service  # Specifies the name of the Service
spec:
  selector:
    app: mysql         # Selects the pods with labels matching 'app: mysql'
  ports:
    - name: mysql      # Specifies the name for the port
      port: 3306       # Sets the port number for the Service
