apiVersion: v1                                      # Defines the API version for the Kubernetes object
kind: ConfigMap                                     # Specifies the kind of Kubernetes object as a ConfigMap
metadata:
  name: mysql-configmap                             # Specifies the name of the ConfigMap
data:
  wait-script.sh: |
    #!/bin/sh
    retries=0
    max_retries=10
    while true; do
      nc -zv mysql 3306 >/dev/null 2>&1
      if [ $? -eq 0 ]; then
        echo "Database is up and running"
        break
      fi
      retries=$((retries+1))
      if [ $retries -eq $max_retries ]; then
        echo "Failed to connect to the database after $retries retries"
        exit 1
      fi
      sleep 5
    done
# Initializes the retries counter
# Sets the maximum number of retries
# Checks if a TCP connection can be established to MySQL on port 3306
# Checks if the previous command was successful
# Prints a message indicating the database is up and running
# Exits the loop
# Increments the retries counter
# Checks if the maximum number of retries has been reached
# Prints a message indicating the connection failure
# Exits the script with a non-zero status code