apiVersion: v1             # Defines the API version for the Kubernetes object
kind: Secret               # Specifies the kind of Kubernetes object as a Secret
metadata:
  name: mysql-secret       # Specifies the name of the Secret
  namespace:  {{ .Values.namespace }}

type: Opaque               # Sets the type of the Secret as Opaque
data:
    MYSQL-root-username: cm9vdA==
    MYSQL-root-password: UEBzc3cwcmQ=
    database_url: amRiYzpteXNxbDovLzEyNy4wLjAuMS9hc3NpZ25tZW50P2FsbG93UHVibGljS2V5UmV0cmlldmFsPXRydWU=
